const sampleTasks = [
  {
    id: 0,
    title: "Eat a vegan meal every day",
    type: "Energy, Environment",
    duration: "1 Week",
    impact: 196,
    why:
      "Aside from improving your physical health and well-being, transitioning to a plant-based diet is one of the most effective ways that you can protect the environment and reduce your carbon footprint.\nThirty percent of the earth's land mass is used for livestock, causing deforestation, erosion, and water pollution. On top of that, the combination of methane released by animals and energy used to raise livestock makes up over 14% of the United States’ greenhouse gas emissions.\nBy becoming Vegan, you’ll be committing to a diet that is healthier for both you and the planet.",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 1,
    title: "Take public transport instead of driving",
    type: "Energy",
    duration: "7",
    impact: 95,
    why:
      "According to the EPA, the transportation sector makes up 27% of US carbon emissions, with the majority of those emissions coming from passenger vehicles. Although fuel efficiency in cars has been improving, the best way to reduce your emissions from driving is simply to take another mode of transportation.\nAt average capacity, all forms of public transport save at least 33% on carbon emissions compared to cars. These savings are even better when at full capacity. As more and more people move to cities, it is important that they advocate for the expansion of public transportation, and the easiest way to do that is to use it!",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 2,
    title: "Bike instead of driving",
    type: "Environment",
    duration: "7",
    impact: 196,
    why: "",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 3,
    title: "Air dry your clothes",
    type: "Energy",
    duration: "7",
    impact: 46,
    why: "",
    currCount: [0],
    currImpact: 0,
    totalCount: 1,
    selected: false,
    completed: false,
  },
  {
    id: 4,
    title: "Carry a reusable water bottle",
    type: "Environment",
    duration: "7",
    impact: 1,
    why: "",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 5,
    title: "Use reusable shopping bag",
    type: "Environment",
    duration: "7",
    impact: 1,
    why: "",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 1,
    selected: false,
    completed: false,
  },
  {
    id: 6,
    title: "Set your thermostat above 72 degrees",
    type: "Energy",
    duration: "7",
    impact: 2.3,
    why: "",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 7,
    title: "Turn off the lights when leaving home",
    type: "Energy",
    duration: "7",
    impact: 1.5,
    why: "",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 8,
    title: "Unplug your electronics",
    type: "Energy",
    duration: "7",
    impact: 39,
    why: "",
    currCount: [0, 0, 0, 0, 0, 0, 0],
    currImpact: 0,
    totalCount: 7,
    selected: false,
    completed: false,
  },
  {
    id: 9,
    title: "Wash clothes on cold",
    type: "Energy",
    duration: "7",
    impact: 7,
    why: "",
    currCount: [0],
    currImpact: 0,
    totalCount: 1,
    selected: false,
    completed: false,
  },
];

export default sampleTasks;
